#!/usr/bin/env bash
#
# Copyright 2021 Lee M. Yeoh (email: "plast-dot-id-dot-au" follows "gitlab")
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# List recent commits for an Arch Linux package (specified as the script's argument)
# Optionally, only display the first NUM commits, using -l NUM.

# Define usage.
usage() {
  cat >&2 <<EOF
Usage: $0 [-l NUM] PACKAGE_NAME | -h
  -l NUM      optionally, only display NUM latest entries
  -h          display this help text and exit
EOF
  exit 1
}

# Parse options.
while getopts 'l:h' opt; do
  case "${opt}" in
    l) length=$OPTARG ;;
    *) usage ;;
  esac
done

# Check -l argument. If $length is empty, then equivalent to flag never being specified. Zero is okay (NOP), negative is not.
if ! [[ $length =~ ^[0-9]*$ ]]; then
  echo 'ERROR: wrong argument supplied to -l'
  usage
  exit 1
fi

shift $((OPTIND-1))

# Check primary argument(s)
if [[ $# != 1 ]]; then
  echo 'ERROR: specify a single package as argument'
  usage
  exit 1
fi

# Determine package's repository
repo=$(pacman -Spdd --print-format %r ${1} 2>/dev/null)

# Determine base package, and start to build url
package_page=$(w3m -dump "https://www.archlinux.org/packages/${repo}/x86_64/${1}/")
base=$(sed -nE 's/^\s*Base Package:\s*(\S*)$/\1/p' <<<"${package_page}")
if [ -z "$base" ]; then
  base="${1}"
fi

case $repo in
core|extra|testing)
  repo_url=packages
  ;;
community|multilib)
  repo_url=community
  ;;
'') # AUR or package not found
  repo_url=aur
  ;;
*)
  echo "ERROR: Unknown repository returned (\"${repo}\")" >&2
  exit 1
  ;;
esac

# Determine terminal's width. Fall back to 80.
term_width=$(tput cols); term_width=${term_width:-80}

# Download and clean output
if [ ! $repo_url = aur ]; then # official repositories
  url="https://github.com/archlinux/svntogit-${repo_url}/commits/packages/${base}/trunk"
  # Download commit log
  output=$(w3m -cols ${term_width} -dump "${url}" | gawk '/^Commits/ {printing="true"}; printing=="true" && !/^$/ && !/^\s+/ && !/^Commits/ {exit}; printing=="true" {print}')
  # Remove whitespace
  clean_output="$(<<<"$output" sed '/^[[:space:]]*$/d')"
  # Remove trailing … (leading ` 1. ` is important if >1 commit per day)
  # Potentially can remove the trailing information on each commit, but it's potentially inconsistent, and maybe some users want to know this?
  clean_output="$(<<<"$clean_output" sed -E 's/\s+…\s*$//')"

else # AUR
  url="https://aur.archlinux.org/cgit/aur.git/log/?h=${base}&showmsg=1"
  # Download commit log
  output=$(w3m -cols ${term_width} -dump "${url}" | sed -n '/Commit message/,/^\s*$/p')
  # Remove "(Collapse)" from header
  clean_output="$(<<<"$output" sed '1 s/(Collapse)/          /')"
fi

# Check for presence of log
if [ -z "$clean_output" ]; then
  echo "ERROR: no log found for ${1}"
  exit 1
fi

# Truncate if necessary
if [ -z $length ]; then
  echo "$clean_output"
else
  if [ ! $repo_url = aur ]; then # official repositories. N.B. ignore 
    <<<"$clean_output" gawk -v l=$length 'BEGIN {nth=0}; ! /^Commits/ && ! /\s+[2-9]\. / {print; next} {if (nth == l){exit} else {print}; nth++}'
  else # AUR
    <<<"$clean_output" gawk -v l=$length 'BEGIN {nth=0}; /^\s/ {print; next} {if (nth == l){exit} else {print}; nth++}'
  fi
fi
